import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
let Registered;const notifications=[];
const sandbox={Float32Array,Number,Math,AudioWorkletProcessor:class{constructor(){this.port={postMessage:m=>notifications.push(m)};}},registerProcessor:(_name,klass)=>{Registered=klass;}};
vm.runInNewContext(await fs.readFile(new URL('./studio/pcm-player.js',import.meta.url),'utf8'),sandbox);
const sink=new Registered();const samples=new Float32Array(6400).fill(.2),out=new Float32Array(128);
sink.process([],[[out]]);assert(out.every(x=>x===0));
sink.port.onmessage({data:{type:'pcm',samples}});sink.process([],[[out]]);assert(out.every(x=>x===0));
for(let i=0;i<13;i++)sink.process([],[[out]]);assert(out.every(x=>Math.abs(x-.2)<1e-6));
sink.port.onmessage({data:{type:'reset'}});sink.process([],[[out]]);assert(out.every(x=>x===0));
sink.port.onmessage({data:{type:'pcm',samples}});sink.port.onmessage({data:{type:'pcm',samples}});sink.process([],[[out]]);assert(out.every(x=>x===0));assert.equal(sink.count,0);assert.equal(notifications[0].type,'overflow');
globalThis.location={pathname:'/unit-test'};
const {ConvertedPlayer}=await import('./studio/player.js');
const received=[];const player=new ConvertedPlayer({routeId:'route',outputKey:'private'});player.node={port:{postMessage:m=>received.push(m)}};
player.receive(JSON.stringify({type:'state',outputKind:'VMOA',sampleRate:40000,chunkSamples:6400,routeId:'route',epoch:9,producerId:'owner',muted:false,mode:'live',reset:true}));
function frame(epoch,seq,age=0){const buffer=new ArrayBuffer(25624),v=new DataView(buffer);new Uint8Array(buffer,0,4).set([86,77,79,65]);v.setUint32(4,epoch,true);v.setUint32(8,seq,true);v.setUint32(12,40000,true);v.setFloat64(16,Date.now()-age,true);new Float32Array(buffer,24).fill(.1);return buffer;}
player.receive(frame(9,0));assert.equal(received.at(-1).type,'pcm');
player.receive(frame(9,1,500));assert.equal(received.at(-1).type,'reset');
player.receive(frame(8,2));assert.equal(received.at(-1).type,'reset');
player.receive(JSON.stringify({type:'state',outputKind:'VMOA',sampleRate:40000,chunkSamples:6400,routeId:'route',epoch:10,producerId:'owner',muted:true,mode:'idle',reset:true}));
player.receive(frame(10,0));assert.equal(received.at(-1).type,'reset');
console.log('PCM checks passed: underflow silence, bounded overflow silence, reset, stale packet, wrong epoch and muted-output rejection.');
const naturalReceived=[];const natural=new ConvertedPlayer({routeId:'natural',outputKey:'separate'},()=>{},()=>{},'natural');natural.node={port:{postMessage:m=>naturalReceived.push(m)}};
natural.receive(JSON.stringify({type:'state',outputKind:'VMNA',sampleRate:40000,chunkSamples:6400,routeId:'natural',epoch:9,producerId:'owner',mode:'natural',muted:false,reset:true}));
natural.receive(frame(9,0));assert.equal(naturalReceived.at(-1).type,'reset');
const naturalFrame=frame(9,0);new Uint8Array(naturalFrame,0,4).set([86,77,78,65]);natural.receive(naturalFrame);assert.equal(naturalReceived.at(-1).type,'pcm');
player.receive(JSON.stringify({type:'state',outputKind:'VMOA',sampleRate:40000,chunkSamples:6400,routeId:'route',epoch:9,producerId:'owner',mode:'live',muted:false,reset:true}));player.receive(naturalFrame);assert.equal(received.at(-1).type,'reset');
console.log('Natural receiver accepts VMNA only; converted receiver rejects natural frames.');
